import { Panel } from './Panel';
import { h, replaceChildren, safeHtml } from '@/utils/dom-utils';
import type { AgentNewsSummary, AgentNewsItem } from '@/types';

const PREDICT_INTERVAL = 30 * 60 * 1000; // 30분

export class PredictPanel extends Panel {
  private latestSummary: AgentNewsSummary | null = null;
  private latestItems: AgentNewsItem[] = [];
  private reportEl: HTMLElement | null = null;
  private timerEl: HTMLElement | null = null;
  private intervalId: ReturnType<typeof setInterval> | null = null;
  private nextRunAt = 0;
  private timerTickId: ReturnType<typeof setInterval> | null = null;
  private generating = false;
  private topicName = '';
  private evolutionGen = 0;
  private lastReportText = '';

  constructor() {
    super({
      id: 'predict',
      title: '\uC628\uD1A8\uB85C\uC9C0 \uAE30\uBC18 AI \uB9AC\uD3EC\uD2B8',
      className: 'predict-panel',
    });
    this.renderInitial();
  }

  private historyTabs: HTMLElement | null = null;
  private reportFiles: string[] = [];

  private renderInitial(): void {
    this.timerEl = h('span', { className: 'predict-timer' }, '');
    this.historyTabs = h('div', { className: 'predict-history-tabs' });
    this.reportEl = h('div', { className: 'predict-report' });

    const header = h('div', { className: 'predict-actions' }, this.timerEl);

    replaceChildren(this.contentEl, header, this.historyTabs, this.reportEl);
  }

  setTopicName(name: string): void {
    this.topicName = name;
  }

  /** Called when new agent news data arrives */
  update(summary: AgentNewsSummary, items?: AgentNewsItem[]): void {
    this.latestSummary = summary;
    if (items) this.latestItems = items;
  }

  /** Start auto-generation cycle (30min interval) */
  startAutoGenerate(): void {
    this.stopAutoGenerate();

    // Immediately load existing report (no loading spinner)
    void this.loadExistingReport();

    // Refresh every 30 minutes
    this.intervalId = setInterval(() => {
      void this.loadExistingReport();
    }, PREDICT_INTERVAL);
  }

  /** Load existing static report without showing loading spinner */
  private async loadExistingReport(): Promise<void> {
    // 1. Load history tabs
    void this.loadHistory();

    // 2. Try static predict-report.json first (already generated by cron)
    const staticReport = await this.loadStaticReport();
    if (staticReport) {
      this.evolutionGen = staticReport.evolutionGen || this.evolutionGen;
      this.lastReportText = staticReport.html;
      this.renderReport(staticReport.html, staticReport.generatedAt);
      this.startCountdown();
      return;
    }

    // 3. No static report → try API only if we have data
    void this.generate();
  }

  stopAutoGenerate(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
    if (this.timerTickId) {
      clearInterval(this.timerTickId);
      this.timerTickId = null;
    }
  }

  private startCountdown(): void {
    this.nextRunAt = Date.now() + PREDICT_INTERVAL;
    if (this.timerTickId) clearInterval(this.timerTickId);
    this.timerTickId = setInterval(() => this.updateTimer(), 1000);
    this.updateTimer();
  }

  private updateTimer(): void {
    if (!this.timerEl) return;
    const remaining = Math.max(0, this.nextRunAt - Date.now());
    const min = Math.floor(remaining / 60000);
    const sec = Math.floor((remaining % 60000) / 1000);
    this.timerEl.textContent = `다음 갱신: ${min}:${String(sec).padStart(2, '0')}`;
  }

  private buildSituationData(): string {
    const parts: string[] = [];

    if (this.latestSummary) {
      parts.push('### 상황 요약');
      parts.push(`- 상황: ${this.latestSummary.situation}`);
      parts.push(`- 인명피해: ${this.latestSummary.casualties}`);
      parts.push(`- 대응: ${this.latestSummary.response}`);
      parts.push(`- 전망: ${this.latestSummary.outlook}`);
      parts.push(`- 마지막 분석: ${this.latestSummary.lastAnalysis}`);
      parts.push('');
    }

    if (this.latestItems.length > 0) {
      parts.push('### 최근 뉴스/제보 (최신순 상위 15건)');
      const recent = this.latestItems.slice(0, 15);
      for (const item of recent) {
        const sev = item.severity === 'critical' ? '🔴' :
                    item.severity === 'high' ? '🟠' :
                    item.severity === 'medium' ? '🟡' : '🟢';
        parts.push(`${sev} [${item.source}] ${item.title}`);
        if (item.description) parts.push(`   ${item.description.slice(0, 120)}`);
        if (item.tags?.length) parts.push(`   태그: ${item.tags.join(', ')}`);
      }
    }

    return parts.join('\n') || '수집된 데이터 없음';
  }

  private async generate(): Promise<void> {
    if (this.generating) return;

    this.generating = true;
    this.renderLoading();

    try {
      // Load history tabs
      void this.loadHistory();

      // 1. Try static predict-report.json (generated by cron job)
      const staticReport = await this.loadStaticReport();
      if (staticReport) {
        this.evolutionGen = staticReport.evolutionGen || this.evolutionGen;
        this.lastReportText = staticReport.html;
        this.renderReport(staticReport.html, staticReport.generatedAt);
        this.startCountdown();
        return;
      }

      // 2. Try API with evolution context
      if (this.latestSummary || this.latestItems.length > 0) {
        const situationData = this.buildSituationData();
        const payload: Record<string, unknown> = {
          situationData,
          topicName: this.topicName || '\uC0C1\uD669 \uBD84\uC11D',
          evolutionGen: this.evolutionGen,
        };
        if (this.lastReportText) {
          payload.previousReport = this.lastReportText.substring(0, 2000);
        }
        const res = await fetch('/api/predict', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        });
        if (res.ok) {
          const data = await res.json() as { report: string; generatedAt: string; evolutionGen?: number };
          this.evolutionGen = data.evolutionGen || this.evolutionGen + 1;
          this.lastReportText = data.report;
          this.renderReport(data.report, data.generatedAt);
          this.startCountdown();
          return;
        }
      }

      // 3. Offline fallback
      this.renderOfflineFallback();
    } catch {
      this.renderOfflineFallback();
    } finally {
      this.generating = false;
    }
  }

  private topicId = 'daejeon-fire';

  setTopicId(id: string): void {
    this.topicId = id;
  }

  private getTopicId(): string {
    return this.topicId;
  }

  private async loadStaticReport(filename?: string): Promise<{ html: string; generatedAt: string; evolutionGen?: number } | null> {
    try {
      const topicId = this.getTopicId();
      const file = filename || 'predict-report.json';
      const res = await fetch(`/data/${topicId}/${file}?t=${Date.now()}`);
      if (!res.ok) return null;
      const data = await res.json();
      if (!data.ontologyAnalysis && !data.predictions && !data.dataSnapshot) return null;

      const html = data.ontologyAnalysis
        ? this.reportJsonToHtml(data)
        : this.reportNewFormatToHtml(data);
      return { html, generatedAt: data.generatedAt || new Date().toISOString(), evolutionGen: data.evolution?.generation };
    } catch {
      return null;
    }
  }

  private async loadHistory(): Promise<void> {
    try {
      const topicId = this.getTopicId();
      const res = await fetch(`/data/${topicId}/predict/index.json?t=${Date.now()}`);
      if (!res.ok) return;
      this.reportFiles = await res.json();
      this.renderHistoryTabs();
    } catch { /* no history yet */ }
  }

  private renderHistoryTabs(): void {
    if (!this.historyTabs || this.reportFiles.length === 0) return;

    const total = this.reportFiles.length;
    // Sort descending: newest first (left) → oldest last (right)
    const sorted = [...this.reportFiles].sort().reverse();
    const recent = sorted.slice(0, 10);
    const tabs = recent.map((file, i) => {
      const m = file.match(/(\d{4})(\d{2})(\d{2})-(\d{2})(\d{2})/);
      const nth = total - i;
      const isFirst = i === 0;
      const label = m ? `${nth}\uCC28 ${m[2]}/${m[3]} ${m[4]}:${m[5]}` : `${nth}\uCC28`;
      const btn = h('button', { className: `summary-tab${isFirst ? ' active' : ''}` }, label);
      btn.addEventListener('click', () => {
        this.historyTabs?.querySelectorAll('.summary-tab').forEach(t => t.classList.remove('active'));
        btn.classList.add('active');
        void this.loadAndShowReport(`predict/${file}`);
      });
      return btn;
    });

    replaceChildren(this.historyTabs!, ...tabs);
  }

  private async loadAndShowReport(filename?: string): Promise<void> {
    const report = await this.loadStaticReport(filename);
    if (report) {
      this.renderReport(report.html, report.generatedAt);
    } else {
      this.renderError('\uB9AC\uD3EC\uD2B8\uB97C \uBD88\uB7EC\uC62C \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.');
    }
  }

  private reportJsonToHtml(data: Record<string, unknown>): string {
    const o = data.ontologyAnalysis as Record<string, unknown>;
    if (!o) return '';

    const ev = o.eventOntology as Record<string, unknown> || {};
    const resrc = o.resourceOntology as Record<string, unknown> || {};
    const cas = o.casualtyOntology as Record<string, unknown> || {};
    const sec = o.secondaryHazardOntology as Record<string, unknown> || o.secondaryHazard as Record<string, unknown> || {};
    const pred = data.predictions as Record<string, unknown> || {};
    const snap = data.dataSnapshot as Record<string, unknown> || {};
    const risks = data.riskMatrix as Array<Record<string, unknown>> || [];
    const conf = data.confidence as Record<string, unknown> || {};

    const section = (title: string, content: string) =>
      `<h4 class="predict-section-title">${title}</h4>${content}`;

    const li = (items: string[]) => items.length
      ? `<ul>${items.map(i => `<li>${i}</li>`).join('')}</ul>` : '';

    let html = '';

    // Data snapshot — natural language
    if (snap.elapsedSinceIgnition) {
      html += `<div class="predict-meta">\u23F1 ${snap.elapsedSinceIgnition} | \uC218\uC9D1 \uB274\uC2A4 ${snap.newsCount || '?'}\uAC74</div>`;
    }

    // Event phase — natural description
    const phaseItems: string[] = [];
    if (ev.phase) phaseItems.push(`\uD604\uC7AC <strong>${ev.phase}</strong> \uB2E8\uACC4\uC785\uB2C8\uB2E4.`);
    if (ev.deltaFromLastReport) phaseItems.push(`${ev.deltaFromLastReport}`);
    const trans = ev.phaseTransition as Record<string, unknown> | undefined;
    if (trans) phaseItems.push(`\uB2E4\uC74C \uB2E8\uACC4\uB294 <strong>${trans.next}</strong>\uC774\uBA70, ${trans.estimatedTransition || ''} \uACBD \uC804\uD658 \uC608\uC0C1\uB429\uB2C8\uB2E4.`);
    if (phaseItems.length) html += section('\uD604\uC7AC \uC0C1\uD669', li(phaseItems));

    // Casualties — clear human language
    const curCas = cas.current as Record<string, unknown> | undefined;
    if (curCas) {
      const casItems = [
        `\uBD80\uC0C1\uC790 <strong>${curCas.injured || '?'}\uBA85</strong> (\uC911\uC0C1 ${curCas.serious || '?'}\uBA85, \uACBD\uC0C1 ${curCas.minor || '?'}\uBA85)`,
        `\uC2E4\uC885\uC790 <strong>${curCas.missing || '?'}\uBA85</strong> \u2014 \uC5F0\uB77D \uB450\uC808 \uC0C1\uD0DC`,
      ];
      const golden = cas.goldenTimeAnalysis as Record<string, unknown> | undefined;
      if (golden) {
        casItems.push(`\uD654\uC7AC \uBC1C\uC0DD \uD6C4 <strong>${golden.elapsedSinceFire}</strong> \uACBD\uACFC. ${golden.goldenTimeStatus || ''}`);
        const surv = golden.survivalProbability as Record<string, unknown> | undefined;
        if (surv) casItems.push(`\uC0DD\uC874 \uAC00\uB2A5\uC131: \uB099\uAD00\uC801 ${surv.optimistic} / \uD604\uC2E4\uC801 ${surv.realistic}`);
      }
      if (cas.deltaFromLastReport) casItems.push(`${cas.deltaFromLastReport}`);
      html += section('\uC778\uBA85 \uD53C\uD574', li(casItems));
    }

    // Secondary hazards — readable
    const hazMat = sec.hazardousMaterials as Record<string, unknown> | undefined;
    const collapse = sec.structuralCollapse as Record<string, unknown> | undefined;
    const envCont = sec.environmentalContamination as Record<string, unknown> | undefined;
    if (hazMat || collapse || envCont) {
      const hazItems: string[] = [];
      if (hazMat) hazItems.push(`<strong>${hazMat.type || '\uB098\uD2B8\uB968'} ${hazMat.quantity || '200kg'}:</strong> ${hazMat.risk || hazMat.status || ''}`);
      if (collapse) hazItems.push(`<strong>\uAC74\uBB3C \uBD95\uAD34 \uC704\uD5D8 (${collapse.risk || '\uB192\uC74C'}):</strong> ${collapse.detail || collapse.implication || ''}`);
      if (envCont) hazItems.push(`<strong>\uD658\uACBD \uC601\uD5A5:</strong> ${envCont.airQuality || ''}`);
      html += section('\uC8FC\uC694 \uC704\uD5D8 \uC694\uC18C', li(hazItems));
    }

    // Predictions — scenario-based natural text
    const shortTerm = pred.shortTerm as Record<string, unknown> | undefined;
    const midTerm = pred.midTerm as Record<string, unknown> | undefined;
    const longTerm = pred.longTerm as Record<string, unknown> | undefined;
    if (shortTerm || midTerm || longTerm) {
      const predItems: string[] = [];
      if (shortTerm) {
        const scenarios = shortTerm.scenarios as Record<string, string> | undefined;
        const prob = shortTerm.probability as Record<string, number> | undefined;
        predItems.push(`<strong>\uB2E8\uAE30 \uC804\uB9DD (${shortTerm.timeframe}):</strong>`);
        if (scenarios) {
          predItems.push(`\uD83D\uDFE2 \uCD5C\uC120: ${scenarios.best}${prob?.best != null ? ` (${Math.round(prob.best * 100)}%)` : ''}`);
          predItems.push(`\uD83D\uDFE1 \uAE30\uBCF8: ${scenarios.baseline}${prob?.baseline != null ? ` (${Math.round(prob.baseline * 100)}%)` : ''}`);
          predItems.push(`\uD83D\uDD34 \uCD5C\uC545: ${scenarios.worst}${prob?.worst != null ? ` (${Math.round(prob.worst * 100)}%)` : ''}`);
        }
      }
      if (midTerm) {
        predItems.push(`<strong>\uC911\uAE30 \uC804\uB9DD (${midTerm.timeframe}):</strong>`);
        if (midTerm.expectedPath) predItems.push(`${midTerm.expectedPath}`);
        if (midTerm.resourceEstimate) predItems.push(`\uD544\uC694 \uC790\uC6D0: ${midTerm.resourceEstimate}`);
      }
      if (longTerm) {
        predItems.push(`<strong>\uC7A5\uAE30 \uC804\uB9DD (${longTerm.timeframe}):</strong>`);
        if (longTerm.phaseExpectation) predItems.push(`${longTerm.phaseExpectation}`);
        const recs = longTerm.recommendations as string[] | undefined;
        if (recs?.length) predItems.push(`\uAD8C\uACE0: ${recs.slice(0, 3).join('; ')}`);
      }
      html += section('\uD5A5\uD6C4 \uC804\uAC1C \uC608\uCE21', li(predItems));
    }

    // Risk matrix — clean table-like display
    if (risks.length > 0) {
      const riskRows = risks.map(r =>
        `<strong>${r.hazard}:</strong> \uBC1C\uC0DD \uAC00\uB2A5\uC131 ${r.probability}, \uC601\uD5A5\uB3C4 ${r.impact} ${r.trend ? `<span style="color:#a78bfa">${r.trend}</span>` : ''}`
      );
      html += section('\uC704\uD5D8 \uD3C9\uAC00', li(riskRows));
    }

    // Confidence — natural
    if (conf.overall) {
      html += `<div class="predict-confidence">\uC608\uCE21 \uC2E0\uB8B0\uB3C4: <strong>${conf.overall}</strong>${conf.changeFromLast ? ` \u2014 ${conf.changeFromLast}` : ''}</div>`;
      const gaps = conf.informationGaps as string[] | undefined;
      if (gaps?.length) {
        html += `<div class="predict-gaps">\uC815\uBCF4 \uBD80\uC871: ${gaps.slice(0, 3).join(' / ')}</div>`;
      }
    }

    // Resources — concise
    const deployed = resrc.deployed as Record<string, unknown> | undefined;
    if (deployed) {
      const resItems = Object.values(deployed).map(v => String(v));
      html += section('\uD22C\uC785 \uC790\uC6D0', `<div class="predict-resource">${resItems.join(' \xB7 ')}</div>`);
    }

    // Evolution log
    const evo = data.evolution as Record<string, unknown> | undefined;
    if (evo) {
      const evoItems: string[] = [];
      if (evo.generation) evoItems.push(`<strong>${evo.generation}\uC138\uB300</strong> \uC608\uCE21 \uB9AC\uD3EC\uD2B8`);
      if (evo.improvements) evoItems.push(`\uC774\uBC88 \uAC1C\uC120: ${evo.improvements}`);
      if (evo.newDimension) evoItems.push(`\uC0C8 \uBD84\uC11D: ${evo.newDimension}`);
      if (evo.nextTask) evoItems.push(`\uB2E4\uC74C \uACFC\uC81C: ${evo.nextTask}`);
      const prevAccuracy = evo.previousAccuracy as string | undefined;
      if (prevAccuracy) evoItems.push(`\uC774\uC804 \uC608\uCE21 \uAC80\uC99D: ${prevAccuracy}`);
      if (evoItems.length) html += section('\uC790\uAE30 \uC9C4\uD654 \uB85C\uADF8', li(evoItems));
    }

    return html;
  }

  private reportNewFormatToHtml(data: Record<string, unknown>): string {
    const snap = data.dataSnapshot as Record<string, unknown> || {};
    const preds = data.predictions as Record<string, unknown> || {};
    const evo = data.evolution as Record<string, unknown> | undefined;
    const confidence = data.confidence as Record<string, unknown> | undefined;

    const section = (title: string, content: string) =>
      `<h4 class="predict-section-title">${title}</h4>${content}`;
    const li = (items: string[]) => items.length
      ? `<ul>${items.map(i => `<li>${i}</li>`).join('')}</ul>` : '';

    let html = '';

    // Data snapshot
    if (snap.elapsedSinceIgnition) {
      html += `<div class="predict-meta">\u23F1 ${snap.elapsedSinceIgnition} | \uC0AC\uB9DD ${snap.deceased ?? '?'} | \uBD80\uC0C1 ${snap.injured ?? '?'} | \uC2E4\uC885 ${snap.missing ?? '?'}</div>`;
    }

    // Predictions
    const predItems: string[] = [];
    if (preds.shortTerm) predItems.push(`<strong>\uB2E8\uAE30:</strong> ${typeof preds.shortTerm === 'string' ? preds.shortTerm : JSON.stringify(preds.shortTerm).replace(/[{}"[\]]/g, '').substring(0, 120)}`);
    if (preds.midTerm) predItems.push(`<strong>\uC911\uAE30:</strong> ${typeof preds.midTerm === 'string' ? preds.midTerm : JSON.stringify(preds.midTerm).replace(/[{}"[\]]/g, '').substring(0, 120)}`);
    if (preds.longTerm) predItems.push(`<strong>\uC7A5\uAE30:</strong> ${typeof preds.longTerm === 'string' ? preds.longTerm : JSON.stringify(preds.longTerm).replace(/[{}"[\]]/g, '').substring(0, 120)}`);
    if (predItems.length) html += section('\uD5A5\uD6C4 \uC804\uAC1C \uC608\uCE21', li(predItems));

    // Confidence
    if (confidence?.overall) {
      html += `<div class="predict-confidence">\uC2E0\uB8B0\uB3C4: ${confidence.overall}</div>`;
    }

    // Evolution
    if (evo) {
      const evoItems: string[] = [];
      if (evo.generation) evoItems.push(`<strong>${evo.generation}\uC138\uB300</strong>`);
      if (evo.improvements) evoItems.push(`\uAC1C\uC120: ${evo.improvements}`);
      if (evo.newDimension) evoItems.push(`\uC0C8 \uBD84\uC11D: ${evo.newDimension}`);
      if (evoItems.length) html += section('\uC9C4\uD654 \uB85C\uADF8', li(evoItems));
    }

    return html;
  }

  private renderLoading(): void {
    if (!this.reportEl) return;
    replaceChildren(this.reportEl,
      h('div', { className: 'predict-loading' },
        h('div', { className: 'predict-spinner' }),
        h('span', {}, '온톨로지 기반 예측 분석 중...'),
      ),
    );
  }


  private renderError(msg: string): void {
    if (!this.reportEl) return;
    replaceChildren(this.reportEl,
      h('div', { className: 'predict-error' }, `예측 생성 실패: ${msg}`),
    );
  }

  private renderOfflineFallback(): void {
    const s = this.latestSummary;
    if (!s || !this.reportEl) {
      this.renderError('데이터 부족으로 오프라인 예측 불가');
      return;
    }

    const isComplete = s.situation?.includes('\uC644\uC804 \uC9C4\uC555') || s.situation?.includes('\uC9C4\uD654 \uC644\uB8CC');
    const progress = isComplete ? '100' : (s.situation?.match(/(\d+)%/)?.[1] || '?');
    const dead = s.casualties?.match(/\uC0AC\uB9DD\s*(\d+)/)?.[1] || '0';
    const missing = s.casualties?.match(/\uC2E4\uC885\s*(\d+)/)?.[1] || '4';
    const injured = s.casualties?.match(/\uBD80\uC0C1\s*(\d+)/)?.[1] || '55';
    const newsCount = this.latestItems.length;

    const report = `<h4 class="predict-section-title">\uC624\uD504\uB77C\uC778 \uC0C1\uD669 \uBD84\uC11D (\uC218\uC9D1 \uB370\uC774\uD130 ${newsCount}\uAC74 \uAE30\uBC18)</h4>
<ul>
<li><strong>\uD604\uC7AC \uB2E8\uACC4:</strong> \uC9C4\uC555 ${progress}%${isComplete ? ' \u2014 \uC9C4\uD654 \uC644\uB8CC, \uC2E4\uC885\uC790 \uC218\uC0C9 \uC911' : ''}</li>
<li><strong>\uC778\uBA85 \uD604\uD669:</strong> \uC0AC\uB9DD ${dead}\uBA85, \uBD80\uC0C1 ${injured}\uBA85, \uC2E4\uC885 ${missing}\uBA85</li>
</ul>
<h4 class="predict-section-title">향후 전개 예측</h4>
<ul>
<li><strong>단기 (1-3시간):</strong> 잔불 완전 진압 후 실종자 수색 개시. 건물 붕괴 위험 평가 선행 필요</li>
<li><strong>중기 (3-12시간):</strong> 실종자 ${missing}명 수색 작업. 나트륨 200kg 안전 처리. 인근 대기질 모니터링</li>
<li><strong>장기 (1-3일):</strong> 사고 원인 조사 착수. 피해 규모 산정. 주민 복귀 결정</li>
</ul>
<h4 class="predict-section-title">주요 위험 요소</h4>
<ul>
<li><strong>나트륨 폭발:</strong> 200kg 보관 — 수색 시 물 사용 제한. 특수 처리 필요</li>
<li><strong>건물 붕괴:</strong> 전소 건물 구조 불안정. 수색 진입 전 안전 평가 필수</li>
<li><strong>대기 오염:</strong> 화학물질 연소 가스 확산 가능. 풍향 모니터링 필요</li>
</ul>
`;

    this.renderReport(report, new Date().toISOString());
    this.startCountdown();
  }

  private renderReport(report: string, generatedAt: string): void {
    if (!this.reportEl) return;

    const time = new Date(generatedAt).toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' });
    const timeEl = h('div', { className: 'predict-timestamp' }, `생성 시각: ${time}`);

    // Convert markdown-style formatting to HTML
    const html = this.formatReport(report);
    const contentEl = h('div', { className: 'predict-content' });
    contentEl.appendChild(safeHtml(html));

    replaceChildren(this.reportEl, timeEl, contentEl);
  }

  private formatReport(text: string): string {
    return text
      .replace(/\*\*\[(.+?)\]\*\*/g, '<h4 class="predict-section-title">$1</h4>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
      .replace(/\n{2,}/g, '<br><br>')
      .replace(/\n/g, '<br>');
  }

  destroy(): void {
    this.stopAutoGenerate();
    super.destroy();
  }
}
